### PR TITLE
[WASI-NN] neural speed: removed due to the upstream end-of-life

### PR DESCRIPTION
**Pull request by hydai**
Ref: https://github.com/intel/neural-speed

### CODE REVIEW

**Comment by hydai** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

## [.github/extensions.paths-filter.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fextensions.paths-filter.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/build-extensions.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Fbuild-extensions.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/matrix-extensions.json](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Fmatrix-extensions.json)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/release.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Frelease.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/reusable-build-extensions.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Freusable-build-extensions.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [cmake/WASINNDeps.cmake](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/cmake%2FWASINNDeps.cmake)

#### Potential issues

N/A

#### Summary of changes

N/A

## [plugins/wasi_nn/CMakeLists.txt](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2FCMakeLists.txt)

#### Potential issues

N/A

#### Summary of changes

N/A

## [plugins/wasi_nn/neuralspeed.cpp](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2Fneuralspeed.cpp)

#### Potential issues

N/A

#### Summary of changes

N/A

## [plugins/wasi_nn/neuralspeed.h](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2Fneuralspeed.h)

#### Potential issues

N/A

#### Summary of changes

N/A

## [test/plugins/wasi_nn/CMakeLists.txt](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/test%2Fplugins%2Fwasi_nn%2FCMakeLists.txt)

#### Potential issues

N/A

#### Summary of changes

N/A

## [test/plugins/wasi_nn/wasi_nn.cpp](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/test%2Fplugins%2Fwasi_nn%2Fwasi_nn.cpp)

#### Potential issues

N/A

#### Summary of changes

N/A

## [utils/wasi-nn/install-neuralspeed.sh](https://github.com/hydai/WasmEdge/blob/7c20731301e4391a3875295ded766fa1593c1ecd/utils%2Fwasi-nn%2Finstall-neuralspeed.sh)

#### Potential issues

N/A

#### Summary of changes

N/A

**Comment by juntao** [comment]
Flows review

**Comment by juntao** [comment]
Flows summarize

**Comment by hydai** [comment]
Flows review

**Comment by hydai** [comment]
Flows review

**Comment by hydai** [comment]
LLM-Reviewer review

**Comment by hydai** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

## [.github/extensions.paths-filter.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fextensions.paths-filter.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/build-extensions.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Fbuild-extensions.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/matrix-extensions.json](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Fmatrix-extensions.json)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/release.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Frelease.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [.github/workflows/reusable-build-extensions.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Freusable-build-extensions.yml)

#### Potential issues

N/A

#### Summary of changes

N/A

## [cmake/WASINNDeps.cmake](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/cmake%2FWASINNDeps.cmake)

#### Potential issues

N/A

#### Summary of changes

N/A

## [plugins/wasi_nn/CMakeLists.txt](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2FCMakeLists.txt)

#### Potential issues

N/A

#### Summary of changes

N/A

## [plugins/wasi_nn/neuralspeed.cpp](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2Fneuralspeed.cpp)

#### Potential issues

N/A

#### Summary of changes

N/A

## [plugins/wasi_nn/neuralspeed.h](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2Fneuralspeed.h)

#### Potential issues

N/A

#### Summary of changes

N/A

## [test/plugins/wasi_nn/CMakeLists.txt](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/test%2Fplugins%2Fwasi_nn%2FCMakeLists.txt)

#### Potential issues

N/A

#### Summary of changes

N/A

## [test/plugins/wasi_nn/wasi_nn.cpp](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/test%2Fplugins%2Fwasi_nn%2Fwasi_nn.cpp)

#### Potential issues

N/A

#### Summary of changes

N/A

## [utils/wasi-nn/install-neuralspeed.sh](https://github.com/hydai/WasmEdge/blob/7c20731301e4391a3875295ded766fa1593c1ecd/utils%2Fwasi-nn%2Finstall-neuralspeed.sh)

#### Potential issues

N/A

#### Summary of changes

N/A

**Comment by hydai** [comment]
LLM-Reviewer summarize

**Comment by hydai** [comment]
Hello, I am a [code review agent](https://github.com/flows-network/github-pr-review/) on [flows.network](https://flows.network/). Here are my reviews of changed source code files in this PR.

------

## [.github/extensions.paths-filter.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fextensions.paths-filter.yml)

#### Potential issues

1. The 'wasi_nn' related files are missing or incomplete - Some parts of the 'wasi_nn' plugin and its tests seem to be missing, which could cause potential errors during execution or testing.
2. Incorrect references to upstream libraries - There may be incorrect or outdated references to upstream libraries in some parts of the code, which can lead to confusion and difficulties in maintaining the project.
3. Inadequate error handling mechanisms - The code lacks adequate error handling mechanisms that could help identify and fix any bugs or issues that arise during execution.

#### Summary of changes

1. Added wasmedge_llmc plugin and its test directory to the list.
2. Reordered the plugins based on their usage in the codebase.
3. Moved the wasmedge_opencvmini plugin and its test directory under the same heading for better organization.

## [.github/workflows/build-extensions.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Fbuild-extensions.yml)

#### Potential issues

[
  This workflow is designed to build and test the WasmEdge project, including its various plugins. It consists of several jobs that build the plugins on different platforms (Ubuntu 20.04, Ubuntu 22.04, Windows Server 2022) using different compilers (GCC/Clang) with different build types (Release).

  The main tasks are:
  1. Checkout the WasmEdge repository and its submodules.
  2. Install required dependencies for building and testing plugins on each platform.
  3. Build the plugins using CMake and Ninja, and compile the tests.
  4. Test the plugins by running their respective test programs.
  5. Prepare a tar.gz package of each built plugin with its related files (like headers) to be used as artifacts for downloading later in the workflow run.

#### Summary of changes

:
1. Removed the "-DWASMEDGE_PLUGIN_WASI_NN_BACKEND=NeuralSpeed" option from build options and corresponding tar names, indicating that the NeuralSpeed backend for WASI-NN has been removed due to upstream end-of-life. 
2. Updated the version of OpenVINO and PyTorch used in the installation process.
3. Modified the Docker image used in the build and test process from "wasmedge/wasmedge:${{ matrix.docker_tag }}" to "wasmedge/wasmedge:latest".

## [.github/workflows/matrix-extensions.json](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Fmatrix-extensions.json)

#### Potential issues

1. The "wasi_nn-whisper" plugin has the same binary as the "wasi_nn-ggml" and "wasi_nn-tensorflowlite" plugins, which may cause confusion and potentially conflicting installations if not handled correctly. 
2. The "wasmedge_opencvmini" plugin is missing from some platform lists, causing inconsistency in supported platforms between different plugins.
3. All the plugins should ideally have the same list of platforms to ensure consistency across all builds. Currently, there are discrepancies among them which may lead to unexpected build failures or mismatches.

#### Summary of changes

1. Added configuration for new WASM Edge plugin "wasmedge_llmc".
2. Extended the platforms for the newly added plugin to include manylinux2014 and manylinux_2_28 aarch64 architecture.
3. Included additional binary files in the list, including wasmedgeLLMCTests.

## [.github/workflows/release.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Frelease.yml)

#### Potential issues

N/A

#### Summary of changes

1. Removed the "wasi_nn-neuralspeed" backend from build options and tar names.
2. Updated the GitHub release command to upload "wasi_nn-ggml" plugin's package.
3. Updated the GitHub release command to upload "wasi_nn-whisper" plugin's package.

## [.github/workflows/reusable-build-extensions.yml](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/.github%2Fworkflows%2Freusable-build-extensions.yml)

#### Potential issues

1. The `on` property in the workflow definition is missing, which could cause the workflow to not run correctly.
2. There's a syntax error in the `if` condition inside the `steps.filter.uses` action. It should be `${{ inputs.release || fromJSON(steps.filter.outputs.all) }}` instead of `!(process.env[plugin.plugin] != 'true')`.
3. The `core.setOutput()` function is called with an incorrect argument inside the `steps.readfile.uses` action. It should be `core.setOutput(tag, JSON.stringify(plugins))` instead of `core.setOutput(tag, plugins)`.

#### Summary of changes

1. Added new job wasmedge_llmc: ${{ steps.filter.outputs.wasmedge_llmc }} 
2. Removed the neural-network related code due to upstream end of life.
3. Updated the list of jobs in the workflow.

## [cmake/WASINNDeps.cmake](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/cmake%2FWASINNDeps.cmake)

#### Potential issues

1. WASI-NN: Neural Speed backend is removed due to the upstream end-of-life. This indicates that there has been a problem with the Neural Speed backend and it was removed from the codebase. It likely doesn't work anymore because the library or service it relies on has reached its end of life, meaning it no longer receives updates or support.
2. Cannot find onnxruntime: This error is raised when the build system cannot locate the onnxruntime package/library required for the piper function. It could be due to incorrect paths provided in the CMakeLists file or the library not being installed on the machine.
3. Error: unused parameter ‘config’ [-Werror=unused-parameter]: This warning is raised when there's a parameter in the source code that isn't used anywhere else, which can be considered as an error because it was defined but never utilized. This could be removed or used in the code to avoid this warning/error.

#### Summary of changes

1. Removal of Neural Speed Backend: The Neural Speed backend has been removed due to the upstream end-of-life, resulting in a message change from indicating build status to a notice. 
2. WASI-NN Build Status Message: Modified the status messages for other backends (GGML and Piper) to reflect their respective builds for WASI-NN.
3. Conditional Compilation Flags: Added conditional compilation flags based on the selected backend, with the Neural Speed flag being removed as it is no longer supported.

## [plugins/wasi_nn/CMakeLists.txt](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2FCMakeLists.txt)

#### Potential issues

1. The WASI-NN's NeuralSpeed backend is removed due to the upstream end-of-life, which might cause issues when the code attempts to use this feature.
2. There seems to be a problem with Python3 library finding and linking in the target_link_libraries command for "chattts" BACKEND. This could prevent the successful compilation of the software if Python3 is not found on the system where it's being built.
3. The code uses FetchContent to download llama.cpp source, but it doesn't specify a version tag which might lead to unstable or unexpected behavior due to different versions having different features and behaviors.

#### Summary of changes

1. Removal of NeuralSpeed backend: The WASI-NN NeuralSpeed backend has been removed due to the upstream end-of-life, as noted in the patch.
2. Setup for SIMDJSON: The script now sets up SIMDJSON, which is a JSON processor library written in C++. 
3. Python3 package search: The patch includes a search for the Python3 package with specific components required - Interpreter and Development.

## [plugins/wasi_nn/neuralspeed.cpp](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2Fneuralspeed.cpp)

#### Potential issues

1. The NeuralSpeed backend has been removed due to the upstream end-of-life, causing a lot of functionality in this file to be nonfunctional.
2. All functions return `reportBackendNotSupported()` which logs an error message and returns an InvalidArgument error code.
3. No further issues were found with the source code.

#### Summary of changes

:
1. Removed the code related to Neural Speed backend, as it's removed due to upstream end-of-life.
2. Updated error messages for better clarity and accuracy.

## [plugins/wasi_nn/neuralspeed.h](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/plugins%2Fwasi_nn%2Fneuralspeed.h)

#### Potential issues

1. The code uses namespaces that are not defined, causing a compilation error - 'WasmEdge::Host::WASINN' namespace is undefined.
2. Function `Context` does not have any parameters to construct the object which could lead to errors during runtime.
3. The function signatures of `load()`, `initExecCtx()`, `setInput()`, `getOutput()`, `compute()` and `unload()` are incomplete thus cannot be used correctly in other parts of the code causing compilation error.

#### Summary of changes

:
1. The Neural Speed backend was removed due to the upstream end-of-life.
2. Python library is no longer being used, which was previously utilized for Neural Speed operations.
3. Graph and Context structures were modified to be empty if Neural Speed backend is not enabled.

## [test/plugins/wasi_nn/CMakeLists.txt](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/test%2Fplugins%2Fwasi_nn%2FCMakeLists.txt)

#### Potential issues

1. The "download" function is not defined before its usage. This will cause an error during the build process.
2. The code attempts to download files from specific GitHub URLs, but doesn't check whether these URLs are accessible or not. If any of them becomes inaccessible, the build process would fail.
3. In the "download" function call, it uses SHA-256 hash for file verification which is not consistent with the rest of the codebase where MD5 hashes are used. Consistency should be maintained throughout the codebase to ensure easy understanding and maintainability of the code.

#### Summary of changes

:
1. Removed "Neural Speed" backend: The patch has removed the support for the "neuralspeed" neural network inference engine, as it's no longer supported or maintained (due to upstream end-of-life). 
2. Download of ML Artifacts: The download process related to the "Neural Speed" backend is also removed.
3. Updated "Piper" backend: The support for the "piper" neural network inference engine remains intact, and it continues to fetch relevant machine learning artifacts into the binary directory.

## [test/plugins/wasi_nn/wasi_nn.cpp](https://github.com/hydai/WasmEdge/blob/1b09b6bded3eb4a3e9de7f1a7c2d08ab97aab27b/test%2Fplugins%2Fwasi_nn%2Fwasi_nn.cpp)

#### Potential issues

N/A

#### Summary of changes

N/A

## [utils/wasi-nn/install-neuralspeed.sh](https://github.com/hydai/WasmEdge/blob/7c20731301e4391a3875295ded766fa1593c1ecd/utils%2Fwasi-nn%2Finstall-neuralspeed.sh)

#### Potential issues

1. The script attempts to install Python dependencies without checking if they are already installed, which could lead to unnecessary re-installs and waste system resources.
2. Using "set -e" at the beginning of the script will stop execution immediately upon encountering any error commands, but it might not catch all errors due to asynchronous operations or other potential failure points in your code.
3. The wget command downloads a file from the web without checking its integrity or availability which can lead to broken installations if the source is unreliable.

#### Summary of changes

1. Python library installation: Python3-dev and python3-pip are installed.
2. Neural Speed Installation: The script attempts to install the Neural Speed Python package, but the upstream project (WASI-NN) has been discontinued or is no longer available due to an end-of-life notification.

**Pull request closed without merging**
